name: quick_log
description: An easy to use and extendable logging package for Dart. Especially useful for use in libraries, as it allows applications to control logging from the imported libraries.
version: 5.3.1
homepage: https://github.com/MohiuddinM/log

environment:
  sdk: ^3.0.0

dependencies:
  path: ^1.8.0
  rxdart: '>=0.26.0 <2.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
