name: quick_log
description: An easy to use and extendable logging package for Dart. Especially useful for use in libraries, as it allows applications to control logging from the imported libraries.
version: 3.0.0
homepage: https://github.com/MohiuddinM/log

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  path: ^1.6.0
  rxdart: '>=0.24.0 <2.0.0'
  equatable: ^1.0.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
