name: quick_log
description: An easy to use and extendable logging package for Dart. Especially useful for use in libraries, as it allows application to control logging from the imported libraries.
version: 0.1.3
homepage: https://github.com/MohiuddinM/log
author: Muhammad Mohiuddin <mohiuddin.android@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  path: ^1.6.0
  rxdart: ^0.22.2
  dart_console: ^0.3.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
